spring:
  datasource:
    url: jdbc:mysql://10.10.10.105:3306/jboot_zziggu?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zziggu
    password: zziggu
    
  mvc:
    view:
      prefix: "/WEB-INF/views/"
      suffix: ".jsp" 
    
mybatis:
  config-location: classpath:mybatis-config.xml  
  
  mapper-locations: classpath:/mapper/*.xml  
  

logging:
   level:
     org.hibernate: info
     org.spingframework: info
     org.zerock: debug
     
     
    